use_frameworks!

target 'YYBottomSheet_Example' do
  pod 'YYBottomSheet', :path => '../'

  target 'YYBottomSheet_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
